name: Keep-Alive Worker

on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping worker to keep it alive
        run: curl -i -X POST ${{ secrets.WORKER_URL }}
